# Generated by Django 5.1.3 on 2024-11-10 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('is_up', models.BooleanField()),
                ('status', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paused', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.CharField(max_length=1024)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('newest_check', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoringapp.check')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoringapp.service')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoringapp.team')),
            ],
        ),
        migrations.AddField(
            model_name='check',
            name='team_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoringapp.teamservice'),
        ),
    ]
