# Generated by Django 5.1.3 on 2024-11-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoringapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='max_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
