# Generated by Django 5.1.3 on 2024-11-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoringapp', '0002_team_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
