# Generated by Django 5.1.3 on 2024-11-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoringapp', '0003_alter_team_max_score_alter_team_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleLock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('locked', models.BooleanField(default=False)),
            ],
        ),
    ]
