# Generated by Django 5.1.3 on 2024-11-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoringapp', '0004_schedulelock'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamservice',
            name='down_checks',
            field=models.IntegerField(default=0),
        ),
    ]
